baseurl = "/"
languageCode = "en-us"
title = "R in Production"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
pluralizeListTitles =   "false"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	author = "RStudio"
	description = "Resources for using R in production."
	copyright = ""
	
	repo_url = "github.com/rstudio/production.rstudio.com"

  version = "1.0.0"
  logo = "/rstudio-logo.png"
  favicon = "favicon.png"

  [params.palette]
    primary = "rstudio-dark"
    accent  = "orange"

  [params.font]
    text = "sans-serif"
    code = "Ubuntu Mono"

[[menu.main]]
  weight = 1
  name = "Getting Started"
  url = "/getting-started/"

[[menu.main]]
  weight = 2
  name = "Managing R"
  url = "/managing-r/"
  
[[menu.main]]
  weight = 3
  name = "Installing R"
  parent = "Managing R"
  url = "/managing-r/install-r/"
  
[[menu.main]]
  weight = 4
  name = "Multiple R Versions"
  parent = "Managing R"
  url = "/managing-r/multiple-r-versions/"
  
[[menu.main]]
  weight = 5
  name = "R Packages"
  parent = "Managing R"
  url = "/managing-r/r-packages/"

[[menu.main]]
  weight = 3
  name = "Developing in R"
  url = "/developing-r/"

[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"


